steps:
    # Step 1: Retrieve the backend-env secret and save it to .env
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Fetch DB certificate'
    waitFor: ['-']
    entrypoint: 'sh'
    args:
      - '-c'
      - 'gcloud secrets versions access latest --secret=db-ca-cert > ca-certificate.crt'

  # Step 2: Retrieve the db-ca-cert secret and save it to /app/src/database/ca-certificate.crt
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Fetch ENV certificate'
    waitFor: ['-']
    entrypoint: 'sh'
    args:
      - '-c'
      - 'gcloud secrets versions access latest --secret=backend-env > .env'

  # Step 3: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/balmy-mile-438210-b9/pickandprice-backend'
      - '.'

  # Step 4: Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image'
    args:
      - 'push'
      - 'gcr.io/balmy-mile-438210-b9/pickandprice-backend'

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy pickandprice-backend \
          --image gcr.io/balmy-mile-438210-b9/pickandprice-backend \
          --platform managed \
          --region africa-south1 \
          --allow-unauthenticated
          
options:
  logging: CLOUD_LOGGING_ONLY